export const MOCK_ARTISTS = [
  {
    id: "luna-ray",
    backendId: 1,
    name: "루나 레이",
    handle: "@lunaray",
    avatar: "https://picsum.photos/seed/luna/200/200",
    cover: "https://picsum.photos/seed/studio/1200/400",
    isLive: true,
    isSubscribed: true,
    isPremiumSubscribed: true,
    memberCount: "120만",
    postCount: 458,
    description:
      "공식 크리에이티브 공간에 오신 것을 환영합니다. 비하인드 스토리, 초기 데모 트랙, 매주 진행되는 라이브 세션을 공유합니다.",
    statusBadge: "LIVE",
    lastUpdateText: "3개의 새로운 업데이트",
    members: [
      {
        id: "luna",
        name: "루나",
        avatar: "https://picsum.photos/seed/luna-member/100/100",
        lastMessage: "팬 여러분, 오늘도 행복한 하루 되세요!",
        lastMessageTime: "오후 10:45",
      },
      {
        id: "ray",
        name: "레이",
        avatar: "https://picsum.photos/seed/ray-member/100/100",
        lastMessage: "연습 끝나고 한 컷!",
        lastMessageTime: "어제",
      },
    ],
  },
  {
    id: "solaris",
    backendId: 2,
    name: "솔라리스",
    handle: "@solaris_music",
    avatar: "https://picsum.photos/seed/sun/200/200",
    cover: "https://picsum.photos/seed/concert/1200/400",
    isLive: false,
    isSubscribed: true,
    isPremiumSubscribed: false,
    memberCount: "85만",
    postCount: 124,
    description: "실험적인 일렉트로닉 사운드와 비주얼 아트를 추구합니다.",
    statusBadge: "NEW GOODS",
    lastUpdateText: "한정판 바이닐 드롭",
    members: [
      {
        id: "sol",
        name: "솔",
        avatar: "https://picsum.photos/seed/sol/100/100",
        lastMessage: "비트 작업 중입니다.",
        lastMessageTime: "2시간 전",
      },
      {
        id: "ari",
        name: "아리",
        avatar: "https://picsum.photos/seed/ari/100/100",
        lastMessage: "오늘 날씨가 너무 좋네요.",
        lastMessageTime: "오전 09:12",
      },
    ],
  },
  {
    id: "neon-dreams",
    backendId: 3,
    name: "네온 드림즈",
    handle: "@neondreams",
    avatar: "https://picsum.photos/seed/neon/200/200",
    cover: "https://picsum.photos/seed/city/1200/400",
    isLive: false,
    isSubscribed: true,
    isPremiumSubscribed: true,
    memberCount: "210만",
    postCount: 890,
    description: "80년대 감성을 현대적인 팝으로 재해석합니다.",
    lastUpdateText: "5분 전 활동",
    members: [
      { id: "neon", name: "네온", avatar: "https://picsum.photos/seed/neon-m/100/100" },
      { id: "dream", name: "드림", avatar: "https://picsum.photos/seed/dream-m/100/100" },
    ],
  },
];

export const MOCK_POSTS = [
  // ——— 루나 레이 아티스트 게시물 ———
  {
    id: "p1",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "루나",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content:
      "오늘 밤 어쿠스틱 세션에서 여러분을 모두 뵙기를 고대하고 있어요! 새 앨범의 수록곡을 살짝 들려드릴 예정입니다. 어떤 노래를 듣고 싶으신가요? ✨",
    image: "https://picsum.photos/seed/mic/800/500",
    likes: "1.2만",
    comments: 842,
    timestamp: "2시간 전",
    type: "ARTIST",
    isArtistExclusive: true,
  },
  {
    id: "p1-2",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "루나",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content:
      "뮤직비디오 촬영 현장에서 한 컷. 곧 티저가 공개됩니다. 기대해 주세요! 🌙",
    image: "https://picsum.photos/seed/mv/800/500",
    likes: "2.1만",
    comments: 1203,
    timestamp: "어제",
    type: "ARTIST",
    isArtistExclusive: true,
  },
  {
    id: "p1-3",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "레이",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content:
      "팬미팅 일정이 확정되었어요. 3월 중순에 만나요! 자세한 일정은 곧 공지할게요.",
    image: null,
    likes: "5.3천",
    comments: 289,
    timestamp: "3일 전",
    type: "ARTIST",
  },
  {
    id: "p1-4",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "루나",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content:
      "새 앨범 작업이 거의 마무리 단계예요. 여러분의 응원이 큰 힘이 됐어요. 감사합니다 💜",
    image: "https://picsum.photos/seed/studio2/800/500",
    likes: "3.8만",
    comments: 2104,
    timestamp: "1주 전",
    type: "ARTIST",
    isArtistExclusive: true,
  },
  {
    id: "p1-5",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "레이",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content: "오늘 라이브에서 선공개했던 곡, 반응이 너무 좋아서 올려요. 편하게 들어보세요!",
    image: null,
    likes: "9.2천",
    comments: 456,
    timestamp: "2주 전",
    type: "ARTIST",
  },
  // ——— 루나 레이 팬 게시물 ———
  {
    id: "pf1",
    artistId: "luna-ray",
    authorName: "별빛팬",
    authorMemberName: "별빛",
    authorAvatar: "https://picsum.photos/seed/fan1/100/100",
    content: "오늘 공연 너무 감동이었어요! 다음에도 꼭 가보고 싶습니다. 루나 레이님 사랑해요 💜",
    image: null,
    likes: "324",
    comments: 28,
    timestamp: "1시간 전",
    type: "FAN",
  },
  {
    id: "pf2",
    artistId: "luna-ray",
    authorName: "달빛",
    authorMemberName: "달빛",
    authorAvatar: "https://picsum.photos/seed/fan2/100/100",
    content: "앨범 미리듣기만 해도 눈물 나요. 정식 발매일이 하루라도 빨리 왔으면!",
    image: "https://picsum.photos/seed/fanpic1/600/400",
    likes: "1.2천",
    comments: 92,
    timestamp: "5시간 전",
    type: "FAN",
  },
  {
    id: "pf3",
    artistId: "luna-ray",
    authorName: "크리에이티브",
    authorMemberName: "크리",
    authorAvatar: "https://picsum.photos/seed/fan3/100/100",
    content: "팬아트 그려봤어요. 루나 레이님 보시면 좋겠네요 ㅎㅎ",
    image: "https://picsum.photos/seed/fanart/600/400",
    likes: "2.8천",
    comments: 156,
    timestamp: "어제",
    type: "FAN",
  },
  {
    id: "pf4",
    artistId: "luna-ray",
    authorName: "음악덕후",
    authorMemberName: "덕후",
    authorAvatar: "https://picsum.photos/seed/fan4/100/100",
    content: "라이브 방송 다시보기 세 번째 보는 중... 매번 새로워요.",
    image: null,
    likes: "567",
    comments: 41,
    timestamp: "2일 전",
    type: "FAN",
  },
  {
    id: "pf5",
    artistId: "luna-ray",
    authorName: "초록별",
    authorMemberName: "초록",
    authorAvatar: "https://picsum.photos/seed/fan5/100/100",
    content: "굿즈 주문했는데 벌써 도착했어요! 품질 대박이에요 👍",
    image: null,
    likes: "189",
    comments: 12,
    timestamp: "4일 전",
    type: "FAN",
  },
  // ——— 루나 레이 공지 ———
  {
    id: "pn1",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "운영팀",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content: "[공지] 3월 팬미팅 일정 및 예매 안내가 곧 공개됩니다. 공식 채널을 통해 확인해 주세요.",
    image: null,
    likes: "0",
    comments: 0,
    timestamp: "2025.02.08",
    type: "NOTICE",
  },
  {
    id: "pn2",
    artistId: "luna-ray",
    authorName: "루나 레이",
    authorMemberName: "운영팀",
    authorAvatar: "https://picsum.photos/seed/luna/200/200",
    content: "[공지] 새 앨범 선주문 기간: 2/15~2/28. 선주문 한정 포토카드가 포함됩니다.",
    image: null,
    likes: "0",
    comments: 0,
    timestamp: "2025.02.05",
    type: "NOTICE",
  },
  // ——— 솔라리스 아티스트 게시물 ———
  {
    id: "p2",
    artistId: "solaris",
    authorName: "솔라리스",
    authorMemberName: "솔",
    authorAvatar: "https://picsum.photos/seed/sun/200/200",
    content: "새로운 한정판 굿즈가 마켓에 공개되었습니다. 확인해보세요!",
    image: "https://picsum.photos/seed/synth/800/500",
    likes: "8.4천",
    comments: 320,
    timestamp: "5시간 전",
    type: "ARTIST",
  },
  {
    id: "p2-2",
    artistId: "solaris",
    authorName: "솔라리스",
    authorMemberName: "아리",
    authorAvatar: "https://picsum.photos/seed/sun/200/200",
    content: "이번 주말 스튜디오 라이브 예정입니다. 곧 시간 공지할게요.",
    image: null,
    likes: "3.2천",
    comments: 198,
    timestamp: "1일 전",
    type: "ARTIST",
  },
  {
    id: "p2-3",
    artistId: "solaris",
    authorName: "솔라리스",
    authorMemberName: "솔",
    authorAvatar: "https://picsum.photos/seed/sun/200/200",
    content: "바이닐 프리오더 마감 D-3. 아직 고민 중이시라면 서둘러 주세요!",
    image: "https://picsum.photos/seed/vinyl2/800/500",
    likes: "1.5천",
    comments: 87,
    timestamp: "3일 전",
    type: "ARTIST",
  },
  // ——— 솔라리스 팬 게시물 ———
  {
    id: "pf6",
    artistId: "solaris",
    authorName: "일렉팬",
    authorMemberName: "일렉",
    authorAvatar: "https://picsum.photos/seed/fan6/100/100",
    content: "솔라리스 라이브 처음 갔는데 분위기 미쳤어요. 다음 공연도 예약 각!",
    image: null,
    likes: "412",
    comments: 33,
    timestamp: "6시간 전",
    type: "FAN",
  },
  {
    id: "pf7",
    artistId: "solaris",
    authorName: "신디사이저",
    authorMemberName: "신디",
    authorAvatar: "https://picsum.photos/seed/fan7/100/100",
    content: "새 앨범 인트로만 10번 넘게 들은 사람 여기 있나요 ㅋㅋ",
    image: null,
    likes: "890",
    comments: 67,
    timestamp: "어제",
    type: "FAN",
  },
  // ——— 네온 드림즈 아티스트 게시물 ———
  {
    id: "p3",
    artistId: "neon-dreams",
    authorName: "네온 드림즈",
    authorMemberName: "네온",
    authorAvatar: "https://picsum.photos/seed/neon/200/200",
    content: "80's Night 콘서트 티켓 오픈했습니다. 링크는 프로필에!",
    image: "https://picsum.photos/seed/neon-concert/800/500",
    likes: "1.8만",
    comments: 654,
    timestamp: "4시간 전",
    type: "ARTIST",
  },
  {
    id: "p3-2",
    artistId: "neon-dreams",
    authorName: "네온 드림즈",
    authorMemberName: "드림",
    authorAvatar: "https://picsum.photos/seed/neon/200/200",
    content: "오늘도 감사한 하루. 여러분 덕분에 무대 위에서 빛날 수 있어요 ✨",
    image: null,
    likes: "4.2천",
    comments: 312,
    timestamp: "2일 전",
    type: "ARTIST",
  },
  // ——— 네온 드림즈 팬 게시물 ———
  {
    id: "pf8",
    artistId: "neon-dreams",
    authorName: "레트로러버",
    authorMemberName: "레트로",
    authorAvatar: "https://picsum.photos/seed/fan8/100/100",
    content: "80년대 감성 + 현대 팝 조합이 진짜 잘 어울려요. 네온 드림즈 최고!",
    image: null,
    likes: "723",
    comments: 45,
    timestamp: "12시간 전",
    type: "FAN",
  },
];

export const MOCK_LIVES = [
  {
    id: "live-now",
    artistId: "luna-ray",
    title: "Luna Ray Q&A",
    status: "LIVE",
    startTime: "LIVE NOW",
    thumbnail: "https://picsum.photos/seed/luna/800/450",
    viewerCount: "1.2만",
    timeLabel: "LIVE NOW",
  },
  {
    id: "live-solaris-now",
    artistId: "solaris",
    title: "Solaris: Studio Live",
    status: "LIVE",
    startTime: "LIVE NOW",
    thumbnail: "https://picsum.photos/seed/sun/800/450",
    viewerCount: "3,240",
    timeLabel: "LIVE NOW",
  },
  {
    id: "live-ended",
    artistId: "luna-ray",
    title: "어쿠스틱 미니 라이브",
    status: "ENDED",
    startTime: "2025.02.01",
    thumbnail: "https://picsum.photos/seed/luna/800/450",
    timeLabel: "종료",
  },
];

export const MOCK_PRODUCTS = [
  {
    id: "prod-1",
    artistId: "luna-ray",
    artistName: "루나 레이",
    name: "Signature Hoodie - Violet",
    price: "65,000원",
    image: "https://picsum.photos/seed/hoodie/400/400",
    description:
      "루나 레이의 시그니처 연보라 후디입니다. 부드러운 기모 소재와 여유로운 핏으로 데일리하게 착용 가능합니다.",
    status: "판매중",
  },
  {
    id: "prod-2",
    artistId: "luna-ray",
    artistName: "루나 레이",
    name: "Signed Vinyl - Moonlit Night",
    price: "45,000원",
    image: "https://picsum.photos/seed/vinyl/400/400",
    description:
      "한정 수량으로 제작된 친필 사인 바이닐입니다. 고품질 180g 중량반으로 깊이 있는 사운드를 선사합니다.",
    status: "판매중",
  },
];

export const MOCK_SETTLEMENTS = [
  { id: "SET-101", date: "2025.02.01", amount: "2,450,000원", status: "완료", type: "GOODS" },
];

export const CANDY_PACKAGES = [
  { id: "c1", amount: 500, price: "5,500원", label: "가벼운 응원" },
  { id: "c2", amount: 1000, price: "11,000원", label: "베스트 셀러" },
  { id: "c3", amount: 3000, price: "33,000원", label: "열혈 팬 전용" },
  { id: "c4", amount: 5000, price: "55,000원", label: "프리미엄 팩" },
  { id: "c5", amount: 10000, price: "99,000원", label: "얼티메이트 세트" },
];

/** 플랫폼 전체 공지사항 (관리자 공지 관리용) */
export const MOCK_NOTICES = [
  { id: 1, title: "시스템 정기 점검 안내 (2025년 3월)", date: "2025.02.20" },
  { id: 2, title: "캔디 충전 이벤트 안내", date: "2025.02.15" },
  { id: 3, title: "개인정보 처리방침 개정 안내", date: "2025.02.12" },
  { id: 4, title: "FanLink 서비스 이용약관 개정 (2025.02)", date: "2025.02.10" },
  { id: 5, title: "결제 시스템 업데이트 완료 안내", date: "2025.02.08" },
  { id: 6, title: "아티스트 정산 일정 변경 안내", date: "2025.02.05" },
  { id: 7, title: "연말 연시 고객센터 운영 안내", date: "2024.12.20" },
  { id: 8, title: "신규 아티스트 가입 이벤트 진행 중", date: "2024.12.15" },
  { id: 9, title: "앱 버전 업데이트 권장 안내 (v2.1)", date: "2024.12.01" },
  { id: 10, title: "불량 계정 및 부정 이용 제재 안내", date: "2024.11.25" },
];
